### ISSUE TITLE
Version 1.7.0 fail to install through pip

### ISSUE THREAD

**Issue by sladedals** [beautify-web/js-beautify#1250]
The newly version 1.7.0 released a few days ago doesn't want to install well through pip.

Here what I obtain : 

```
Collecting jsbeautifier (from py_package->-r local_requirements.txt (line 1))
   Downloading jsbeautifier-1.7.0.tar.gz
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-_oun2mqe/jsbeautifier/setup.py", line 6, in <module>
         from jsbeautifier.__version__ import __version__
       File "/tmp/pip-build-_oun2mqe/jsbeautifier/jsbeautifier/__init__.py", line 11, in <module>
         from jsbeautifier.javascript.options import BeautifierOptions
ModuleNotFoundError: No module named 'jsbeautifier.javascript'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_oun2mqe/jsbeautifier/
```

And, well, it seems to be right, I can't find any trace of javascript.py file anywhere in the source release.

When I look at [the setup.py](https://github.com/beautify-web/js-beautify/blob/master/python/setup.py#L33), I can guess the problem, you forgot to add 'jsbeautifier.javascript' to the list of packages, so setup.py won't bring it when making the archive.

Maybe with this it will be better
```

      packages=['jsbeautifier', 'jsbeautifier.tests', 'jsbeautifier.tests.generated',
                'jsbeautifier.unpackers', 'jsbeautifier.unpackers.tests', 'jsbeautifer.javascript'],
```

**Comment by wssgcg1213** [comment]
+1

**Comment by bitwiseman** [comment]
@sladedals - Thanks for the detailed bug report.

**Comment by bitwiseman** [comment]
See #1254.  Tests will be implemented to protect against this in the future.
