### ISSUE TITLE
Unhelpful error when .jsbeautifyrc has invalid json

### ISSUE THREAD

**Issue by michaeljones** [beautify-web/js-beautify#728]
### Steps to reproduce:

0. `mkdir tmp; cd tmp`
0. `echo "{" > .jsbeautifyrc`
0. `js-beautify`

### Expected result:
Nice error message about poorly formed `.jsbeautifyrc` content.

### Actual result:
```
$ js-beautify
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at exports.parse (/home/mike/.nave/installed/0.12.5/lib/node_modules/js-beautify/node_modules/config-chain/index.js:54:19)
    at exports.json (/home/mike/.nave/installed/0.12.5/lib/node_modules/js-beautify/node_modules/config-chain/index.js:70:10)
    at module.exports (/home/mike/.nave/installed/0.12.5/lib/node_modules/js-beautify/node_modules/config-chain/index.js:17:15)
    at Object.exports.interpret (/home/mike/.nave/installed/0.12.5/lib/node_modules/js-beautify/js/lib/cli.js:173:15)
    at Object.<anonymous> (/home/mike/.nave/installed/0.12.5/lib/node_modules/js-beautify/js/bin/js-beautify.js:4:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
### Environment

- **js-beautify**: 1.5.10
- **os**: Ubuntu
- **node**: v0.12.5

### Notes

I think the project is great! Thanks for writing it! But this confused me somewhat. I was running `js-beautify` on an actual file and though that the `SyntaxError` was in the file instead of my config. Took a while to click!

Kind regards,
Michael

**Comment by bitwiseman** [comment]
Thanks for the good issue description.  Will fix in the next version.
